apiVersion: v1
kind: Service

metadata:
  name: maven-nexus-demo
  namespace: maven-demo

spec:
  type: NodePort

  selector:
    app: maven-nexus-demo

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
